oslsim:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  hipL_position_controller:
    type: effort_controllers/JointPositionController
    joint: hipL
    pid: {p: 400, i: 1.0, d: 10.0}

  hipR_position_controller:
    type: effort_controllers/JointPositionController
    joint: hipR
    pid: {p: 400, i: 1.0, d: 10.0}

  kneeL_position_controller:
    type: effort_controllers/JointPositionController
    joint: kneeL
    pid: {p: 400, i: 1.0, d: 10.0}

  kneeR_position_controller:
    type: effort_controllers/JointPositionController
    joint: kneeR
    pid: {p: 400, i: 1.0, d: 10.0}

  ankleL_position_controller:
    type: effort_controllers/JointPositionController
    joint: ankleL
    pid: {p: 400, i: 1.0, d: 10.0}

  ankleR_position_controller:
    type: effort_controllers/JointPositionController
    joint: ankleR
    pid: {p: 400, i: 1.0, d: 10.0}

