oslsim:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  hip_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip
    pid: {p: 10, i: 0.1, d: 0.01}

  osl_hip_position_controller:
    type: effort_controllers/JointPositionController
    joint: osl_hip
    pid: {p: 10, i: 0.1, d: 0.01}

  knee_position_controller:
    type: effort_controllers/JointPositionController
    joint: knee
    pid: {p: 10, i: 0.1, d: 0.01}

  osl_knee_position_controller:
    type: effort_controllers/JointPositionController
    joint: osl_knee
    pid: {p: 10, i: 0.1, d: 0.01}

  ankle_position_controller:
    type: effort_controllers/JointPositionController
    joint: ankle
    pid: {p: 10, i: 0.1, d: 0.01}

  osl_ankle_position_controller:
    type: effort_controllers/JointPositionController
    joint: osl_ankle
    pid: {p: 10, i: 0.1, d: 0.01}

