oslsim:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  hipL_position_controller:
    type: effort_controllers/JointPositionController
    joint: hipL
    pid: {p: 10, i: 0.1, d: 0.01}

  hipR_position_controller:
    type: effort_controllers/JointPositionController
    joint: hipR
    pid: {p: 10, i: 0.1, d: 0.01}

  kneeL_position_controller:
    type: effort_controllers/JointPositionController
    joint: kneeL
    pid: {p: 10, i: 0.1, d: 0.01}

  kneeR_position_controller:
    type: effort_controllers/JointPositionController
    joint: kneeR
    pid: {p: 10, i: 0.1, d: 0.01}

  ankleL_position_controller:
    type: effort_controllers/JointPositionController
    joint: ankleL
    pid: {p: 10, i: 0.1, d: 0.01}

  ankleR_position_controller:
    type: effort_controllers/JointPositionController
    joint: ankleR
    pid: {p: 10, i: 0.1, d: 0.01}

